// === DATA STORE ===
// Centralised listings array — easy to swap with a real backend API
// Photo quality note: We use Unsplash for now; backend enforces min resolution 1200x800 on upload

const LISTINGS = [
  {
    id: 1,
    title: "Modern 2BR Apartment, Kilimani",
    region: "Nairobi",
    neighbourhood: "Kilimani",
    type: "2 Bedrooms",
    bedrooms: 2,
    bathrooms: 2,
    size: 85, // sqm
    price: 55000,
    available: true,
    verified: true,
    description: "Spacious and fully finished 2-bedroom apartment in the heart of Kilimani. Features high ceilings, balcony views, and a modern kitchen. Backup generator and borehole water included. Close to Yaya Centre and Junction Mall.",
    amenities: ["Parking", "Security", "Generator", "Borehole Water", "Balcony", "WiFi Ready", "CCTV"],
    phone: "+254 712 345 678",
    photos: [
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=900&q=85",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=900&q=85"
    ],
    dateAdded: "2025-01-10",
  },
  {
    id: 2,
    title: "Cosy Bedsitter, Westlands",
    region: "Nairobi",
    neighbourhood: "Westlands",
    type: "Bedsitter",
    bedrooms: 0,
    bathrooms: 1,
    size: 28,
    price: 18000,
    available: true,
    verified: true,
    description: "Clean, recently renovated bedsitter in a secure compound in Westlands. Ideal for a working professional. Good water supply, tiled floors, and 24hr security. Close to major offices and restaurants.",
    amenities: ["Security", "Tiled Floors", "Water 24hr", "Quiet Area"],
    phone: "+254 722 111 222",
    photos: [
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=900&q=85"
    ],
    dateAdded: "2025-01-08",
  },
  {
    id: 3,
    title: "Executive 3BR Maisonette, Karen",
    region: "Nairobi",
    neighbourhood: "Karen",
    type: "Maisonette",
    bedrooms: 3,
    bathrooms: 2.5,
    size: 180,
    price: 120000,
    available: true,
    verified: true,
    description: "Stunning maisonette in Karen set on a lush, landscaped compound. Features open-plan living, fitted kitchen, DSQ (boys quarters), and ample parking. Very serene environment — ideal for families.",
    amenities: ["DSQ", "Parking x2", "Garden", "Borehole Water", "Generator", "Security 24hr", "Fitted Kitchen"],
    phone: "+254 733 999 888",
    photos: [
      "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=900&q=85",
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=900&q=85"
    ],
    dateAdded: "2025-01-05",
  },
  {
    id: 4,
    title: "1BR Apartment, Nyali Beach Road",
    region: "Mombasa",
    neighbourhood: "Nyali",
    type: "1 Bedroom",
    bedrooms: 1,
    bathrooms: 1,
    size: 50,
    price: 25000,
    available: true,
    verified: true,
    description: "Beautiful 1-bedroom apartment near Nyali Beach. Ocean breeze, sea views from the balcony, and a communal swimming pool. Perfect for couples or singles wanting the coastal lifestyle.",
    amenities: ["Swimming Pool", "Balcony", "Sea View", "Security", "Backup Water", "Parking"],
    phone: "+254 700 456 789",
    photos: [
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=900&q=85"
    ],
    dateAdded: "2025-01-07",
  },
  {
    id: 5,
    title: "Studio Apartment, Milimani Estate",
    region: "Kisumu",
    neighbourhood: "Milimani",
    type: "Studio",
    bedrooms: 0,
    bathrooms: 1,
    size: 35,
    price: 15000,
    available: true,
    verified: false,
    description: "Modern studio apartment in Kisumu's upmarket Milimani area. Lake views, tiled throughout, and fitted wardrobe. Water included in rent. Walking distance to Kisumu CBD.",
    amenities: ["Lake View", "Tiled Floors", "Water Included", "Security", "Fitted Wardrobe"],
    phone: "+254 711 222 333",
    photos: [
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=900&q=85"
    ],
    dateAdded: "2025-01-09",
  },
  {
    id: 6,
    title: "4BR Family Home, Ngong Road",
    region: "Nairobi",
    neighbourhood: "Rongai",
    type: "4+ Bedrooms",
    bedrooms: 4,
    bathrooms: 3,
    size: 220,
    price: 85000,
    available: true,
    verified: true,
    description: "Spacious 4-bedroom home along Ngong Road corridor. Large compound with a garden, garage for 3 cars, and a DSQ. Ideal for large families. KPLC prepaid metering, own borehole.",
    amenities: ["Garage x3", "DSQ", "Garden", "Borehole", "Prepaid Meter", "Security", "CCTV"],
    phone: "+254 725 887 654",
    photos: [
      "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=900&q=85"
    ],
    dateAdded: "2025-01-06",
  },
  {
    id: 7,
    title: "Affordable 1BR, Pipeline Estate",
    region: "Nairobi",
    neighbourhood: "Embakasi",
    type: "1 Bedroom",
    bedrooms: 1,
    bathrooms: 1,
    size: 40,
    price: 9500,
    available: true,
    verified: true,
    description: "Clean and affordable 1-bedroom house in Pipeline. Good security, reliable water supply. Best for young professionals and couples on a budget.",
    amenities: ["Security", "Reliable Water", "Quiet Compound"],
    phone: "+254 798 001 002",
    photos: [
      "https://images.unsplash.com/photo-1507089947368-19c1da9775ae?w=900&q=85"
    ],
    dateAdded: "2025-01-11",
  },
  {
    id: 8,
    title: "2BR Flat, Old Town Mombasa",
    region: "Mombasa",
    neighbourhood: "Old Town",
    type: "2 Bedrooms",
    bedrooms: 2,
    bathrooms: 1,
    size: 65,
    price: 19000,
    available: true,
    verified: false,
    description: "Charming 2-bedroom flat in Mombasa's historic Old Town. Beautiful Swahili-style architecture, wooden ceilings, and a rooftop terrace. Walking distance to Fort Jesus and the ferry.",
    amenities: ["Rooftop Terrace", "Historic Building", "Central Location"],
    phone: "+254 741 123 456",
    photos: [
      "https://images.unsplash.com/photo-1464082354059-27db6ce50048?w=900&q=85"
    ],
    dateAdded: "2025-01-04",
  },
  {
    id: 9,
    title: "Luxury 3BR Penthouse, Upperhill",
    region: "Nairobi",
    neighbourhood: "Upperhill",
    type: "3 Bedrooms",
    bedrooms: 3,
    bathrooms: 3,
    size: 160,
    price: 220000,
    available: true,
    verified: true,
    description: "Top-floor penthouse with panoramic Nairobi city views. Floor-to-ceiling windows, fully fitted chef's kitchen, jacuzzi, private terrace, and a private lift lobby. Premium, concierge-level security.",
    amenities: ["City View", "Jacuzzi", "Private Terrace", "Gym", "Concierge", "Generator", "Secure Parking", "Lift"],
    phone: "+254 700 111 999",
    photos: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=900&q=85"
    ],
    dateAdded: "2025-01-03",
  },
  {
    id: 10,
    title: "Bedsitter, Nakuru Town Centre",
    region: "Nakuru",
    neighbourhood: "Section 58",
    type: "Bedsitter",
    bedrooms: 0,
    bathrooms: 1,
    size: 22,
    price: 6500,
    available: true,
    verified: true,
    description: "Affordable bedsitter in a clean compound in Nakuru. Close to Nakuru National Park and the CBD. Running water, tiled floors. Suitable for students and young workers.",
    amenities: ["Running Water", "Tiled", "Secure Compound"],
    phone: "+254 715 333 444",
    photos: [
      "https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=900&q=85"
    ],
    dateAdded: "2025-01-12",
  },
  {
    id: 11,
    title: "3BR Bungalow, Eldoret Town",
    region: "Eldoret",
    neighbourhood: "Elgon View",
    type: "3 Bedrooms",
    bedrooms: 3,
    bathrooms: 2,
    size: 110,
    price: 35000,
    available: true,
    verified: true,
    description: "Lovely 3-bedroom bungalow with a landscaped garden in Eldoret's leafy Elgon View estate. Kids-friendly compound, ample parking, and 24hr security.",
    amenities: ["Garden", "Parking", "Security 24hr", "Borehole", "KPLC Prepaid"],
    phone: "+254 720 555 666",
    photos: [
      "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=900&q=85"
    ],
    dateAdded: "2025-01-01",
  },
  {
    id: 12,
    title: "2BR Ocean-view Apartment, Malindi",
    region: "Malindi",
    neighbourhood: "Silversands",
    type: "2 Bedrooms",
    bedrooms: 2,
    bathrooms: 2,
    size: 90,
    price: 38000,
    available: true,
    verified: true,
    description: "Stunning 2-bedroom apartment 200m from Silversands Beach in Malindi. Ocean views, private balcony, and fully furnished. Ideal as a holiday rental or long-stay.",
    amenities: ["Ocean View", "Furnished", "Pool", "Balcony", "Parking", "Security", "Backup Water"],
    phone: "+254 700 888 777",
    photos: [
      "https://images.unsplash.com/photo-1528909514045-2fa4ac7a08ba?w=900&q=85"
    ],
    dateAdded: "2025-01-02",
  }
];

const REGIONS = [
  { name: "Nairobi", emoji: "🏙️", description: "Capital City" },
  { name: "Mombasa", emoji: "🌊", description: "Coastal City" },
  { name: "Kisumu", emoji: "🌅", description: "Lakeside City" },
  { name: "Nakuru", emoji: "🦩", description: "The Flower City" },
  { name: "Eldoret", emoji: "🏃", description: "City of Champions" },
  { name: "Thika", emoji: "🌿", description: "Blue Posts Town" },
  { name: "Nyeri", emoji: "🏔️", description: "Mt. Kenya Gateway" },
  { name: "Malindi", emoji: "🐠", description: "Coastal Resort Town" }
];